//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Details.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string empName { get; set; }
        public string empMobile { get; set; }
        public string empAddress { get; set; }
        public string empDept { get; set; }
        public int empId { get; set; }
    }
}
